spring:
  application:
    name: "order-application"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/todo}
    password: ${DATASOURCE_PASSWORD:1q2w3e4r}
    username: ${DATASOURCE_USERNAME:root}
server:
  port: 8081
kafka:
  server: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
  topics:
    order: "ex_order"
    item: "ex_item"

