spring:
  application:
    name: "item-application"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/item_db?createDatabaseIfNotExist=true}
    password: ${DATASOURCE_PASSWORD:1q2w3e4r}
    username: ${DATASOURCE_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USER:root}
      password: ${MONGODB_PASSWORD:1q2w3e4r}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
server:
  port: 8080
kafka:
  broker:
    url: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
